### ISSUE TITLE
Incorrectly calculating the latitude

### ISSUE THREAD

**Issue by tsellste** [Esri/trimble-for-geoevent#2]
I recently added the trimble-for-geoevent connector to our GeoEvent Server.  We use the TAIP LN message for all of our AVL positions.  When using this connector it is calculating the latitude incorrectly by a factor of 10.  After looking at your code the only translator that is calculating latitude correctly is the TAIP0xF0 translator.  The other translators all multiply Y with an extra decimal place.  For testing purposes on our GeoEvent Server I switched our gateways to use the TAIP PV message and started using the TAIP0xF0 translator which works well.

I am not a Java Developer so I don't have an IDE set up to fix this issue and wanted you to be aware of it.  Thanks very much!

Added 08/13/2018:  It would be great if this was issue could be addressed before they put together the release for 10.6.  Thanks very much for your consideration!

Regards,
Tom

**Comment by tsellste** [comment]
Greetings!  I was asked by ESRI support to make another request to fix this issue as they are getting ready to update the adapter to 10.6.x.  If possible, it would be great to have the option of using the TAIP0xF2 - TAIP LN messages on our geoevent server.  Thanks for your consideration!

**Comment by eironside** [comment]
Fixed in latest release.
